/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedSyncIndexRouteImport } from './routes/_authenticated/sync/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedCoursesIndexRouteImport } from './routes/_authenticated/courses/index'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedCoursesCourseIdRouteRouteImport } from './routes/_authenticated/courses/$courseId/route'
import { Route as AuthenticatedCoursesCourseIdIndexRouteImport } from './routes/_authenticated/courses/$courseId/index'
import { Route as AuthenticatedCoursesCourseIdStreamRouteImport } from './routes/_authenticated/courses/$courseId/stream'
import { Route as AuthenticatedCoursesCourseIdPeopleRouteImport } from './routes/_authenticated/courses/$courseId/people'
import { Route as AuthenticatedCoursesCourseIdClassworkRouteImport } from './routes/_authenticated/courses/$courseId/classwork'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSyncIndexRoute = AuthenticatedSyncIndexRouteImport.update({
  id: '/sync/',
  path: '/sync/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedCoursesIndexRoute =
  AuthenticatedCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdRouteRoute =
  AuthenticatedCoursesCourseIdRouteRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdIndexRoute =
  AuthenticatedCoursesCourseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCoursesCourseIdRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdStreamRoute =
  AuthenticatedCoursesCourseIdStreamRouteImport.update({
    id: '/stream',
    path: '/stream',
    getParentRoute: () => AuthenticatedCoursesCourseIdRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdPeopleRoute =
  AuthenticatedCoursesCourseIdPeopleRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => AuthenticatedCoursesCourseIdRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdClassworkRoute =
  AuthenticatedCoursesCourseIdClassworkRouteImport.update({
    id: '/classwork',
    path: '/classwork',
    getParentRoute: () => AuthenticatedCoursesCourseIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRouteRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/courses/': typeof AuthenticatedCoursesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/sync/': typeof AuthenticatedSyncIndexRoute
  '/courses/$courseId/classwork': typeof AuthenticatedCoursesCourseIdClassworkRoute
  '/courses/$courseId/people': typeof AuthenticatedCoursesCourseIdPeopleRoute
  '/courses/$courseId/stream': typeof AuthenticatedCoursesCourseIdStreamRoute
  '/courses/$courseId/': typeof AuthenticatedCoursesCourseIdIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/courses': typeof AuthenticatedCoursesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/sync': typeof AuthenticatedSyncIndexRoute
  '/courses/$courseId/classwork': typeof AuthenticatedCoursesCourseIdClassworkRoute
  '/courses/$courseId/people': typeof AuthenticatedCoursesCourseIdPeopleRoute
  '/courses/$courseId/stream': typeof AuthenticatedCoursesCourseIdStreamRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/courses/$courseId': typeof AuthenticatedCoursesCourseIdRouteRouteWithChildren
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/courses/': typeof AuthenticatedCoursesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/sync/': typeof AuthenticatedSyncIndexRoute
  '/_authenticated/courses/$courseId/classwork': typeof AuthenticatedCoursesCourseIdClassworkRoute
  '/_authenticated/courses/$courseId/people': typeof AuthenticatedCoursesCourseIdPeopleRoute
  '/_authenticated/courses/$courseId/stream': typeof AuthenticatedCoursesCourseIdStreamRoute
  '/_authenticated/courses/$courseId/': typeof AuthenticatedCoursesCourseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/courses/$courseId'
    | '/errors/$error'
    | '/courses/'
    | '/settings/'
    | '/sync/'
    | '/courses/$courseId/classwork'
    | '/courses/$courseId/people'
    | '/courses/$courseId/stream'
    | '/courses/$courseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/courses'
    | '/settings'
    | '/sync'
    | '/courses/$courseId/classwork'
    | '/courses/$courseId/people'
    | '/courses/$courseId/stream'
    | '/courses/$courseId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/courses/$courseId'
    | '/_authenticated/errors/$error'
    | '/_authenticated/courses/'
    | '/_authenticated/settings/'
    | '/_authenticated/sync/'
    | '/_authenticated/courses/$courseId/classwork'
    | '/_authenticated/courses/$courseId/people'
    | '/_authenticated/courses/$courseId/stream'
    | '/_authenticated/courses/$courseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sync/': {
      id: '/_authenticated/sync/'
      path: '/sync'
      fullPath: '/sync/'
      preLoaderRoute: typeof AuthenticatedSyncIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/courses/': {
      id: '/_authenticated/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AuthenticatedCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$courseId': {
      id: '/_authenticated/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$courseId/': {
      id: '/_authenticated/courses/$courseId/'
      path: '/'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdIndexRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRouteRoute
    }
    '/_authenticated/courses/$courseId/stream': {
      id: '/_authenticated/courses/$courseId/stream'
      path: '/stream'
      fullPath: '/courses/$courseId/stream'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdStreamRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRouteRoute
    }
    '/_authenticated/courses/$courseId/people': {
      id: '/_authenticated/courses/$courseId/people'
      path: '/people'
      fullPath: '/courses/$courseId/people'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdPeopleRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRouteRoute
    }
    '/_authenticated/courses/$courseId/classwork': {
      id: '/_authenticated/courses/$courseId/classwork'
      path: '/classwork'
      fullPath: '/courses/$courseId/classwork'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdClassworkRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedCoursesCourseIdRouteRouteChildren {
  AuthenticatedCoursesCourseIdClassworkRoute: typeof AuthenticatedCoursesCourseIdClassworkRoute
  AuthenticatedCoursesCourseIdPeopleRoute: typeof AuthenticatedCoursesCourseIdPeopleRoute
  AuthenticatedCoursesCourseIdStreamRoute: typeof AuthenticatedCoursesCourseIdStreamRoute
  AuthenticatedCoursesCourseIdIndexRoute: typeof AuthenticatedCoursesCourseIdIndexRoute
}

const AuthenticatedCoursesCourseIdRouteRouteChildren: AuthenticatedCoursesCourseIdRouteRouteChildren =
  {
    AuthenticatedCoursesCourseIdClassworkRoute:
      AuthenticatedCoursesCourseIdClassworkRoute,
    AuthenticatedCoursesCourseIdPeopleRoute:
      AuthenticatedCoursesCourseIdPeopleRoute,
    AuthenticatedCoursesCourseIdStreamRoute:
      AuthenticatedCoursesCourseIdStreamRoute,
    AuthenticatedCoursesCourseIdIndexRoute:
      AuthenticatedCoursesCourseIdIndexRoute,
  }

const AuthenticatedCoursesCourseIdRouteRouteWithChildren =
  AuthenticatedCoursesCourseIdRouteRoute._addFileChildren(
    AuthenticatedCoursesCourseIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCoursesCourseIdRouteRoute: typeof AuthenticatedCoursesCourseIdRouteRouteWithChildren
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedCoursesIndexRoute: typeof AuthenticatedCoursesIndexRoute
  AuthenticatedSyncIndexRoute: typeof AuthenticatedSyncIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCoursesCourseIdRouteRoute:
    AuthenticatedCoursesCourseIdRouteRouteWithChildren,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedCoursesIndexRoute: AuthenticatedCoursesIndexRoute,
  AuthenticatedSyncIndexRoute: AuthenticatedSyncIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
