/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedTodosIndexRouteImport } from './routes/_authenticated/todos/index'
import { Route as AuthenticatedSyncIndexRouteImport } from './routes/_authenticated/sync/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSearchIndexRouteImport } from './routes/_authenticated/search/index'
import { Route as AuthenticatedCoursesIndexRouteImport } from './routes/_authenticated/courses/index'
import { Route as AuthenticatedBotIndexRouteImport } from './routes/_authenticated/bot/index'
import { Route as AuthenticatedAuditIndexRouteImport } from './routes/_authenticated/audit/index'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings/users'
import { Route as AuthenticatedSettingsSetupRouteImport } from './routes/_authenticated/settings/setup'
import { Route as AuthenticatedSettingsSchedulerRouteImport } from './routes/_authenticated/settings/scheduler'
import { Route as AuthenticatedSettingsRolesRouteImport } from './routes/_authenticated/settings/roles'
import { Route as AuthenticatedSettingsLanguageRouteImport } from './routes/_authenticated/settings/language'
import { Route as AuthenticatedSettingsBackupRouteImport } from './routes/_authenticated/settings/backup'
import { Route as AuthenticatedSettingsAuditRouteImport } from './routes/_authenticated/settings/audit'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as authAdminLoginRouteImport } from './routes/(auth)/admin/login'
import { Route as AuthenticatedCoursesCourseIdRouteRouteImport } from './routes/_authenticated/courses/$courseId/route'
import { Route as AuthenticatedCoursesCourseIdIndexRouteImport } from './routes/_authenticated/courses/$courseId/index'
import { Route as AuthenticatedCoursesCourseIdStreamRouteImport } from './routes/_authenticated/courses/$courseId/stream'
import { Route as AuthenticatedCoursesCourseIdPeopleRouteImport } from './routes/_authenticated/courses/$courseId/people'
import { Route as AuthenticatedCoursesCourseIdClassworkRouteImport } from './routes/_authenticated/courses/$courseId/classwork'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTodosIndexRoute = AuthenticatedTodosIndexRouteImport.update({
  id: '/todos/',
  path: '/todos/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSyncIndexRoute = AuthenticatedSyncIndexRouteImport.update({
  id: '/sync/',
  path: '/sync/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSearchIndexRoute =
  AuthenticatedSearchIndexRouteImport.update({
    id: '/search/',
    path: '/search/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesIndexRoute =
  AuthenticatedCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBotIndexRoute = AuthenticatedBotIndexRouteImport.update({
  id: '/bot/',
  path: '/bot/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditIndexRoute = AuthenticatedAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsSetupRoute =
  AuthenticatedSettingsSetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsSchedulerRoute =
  AuthenticatedSettingsSchedulerRouteImport.update({
    id: '/scheduler',
    path: '/scheduler',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsRolesRoute =
  AuthenticatedSettingsRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsLanguageRoute =
  AuthenticatedSettingsLanguageRouteImport.update({
    id: '/language',
    path: '/language',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsBackupRoute =
  AuthenticatedSettingsBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAuditRoute =
  AuthenticatedSettingsAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const authAdminLoginRoute = authAdminLoginRouteImport.update({
  id: '/(auth)/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoursesCourseIdRouteRoute =
  AuthenticatedCoursesCourseIdRouteRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdIndexRoute =
  AuthenticatedCoursesCourseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCoursesCourseIdRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdStreamRoute =
  AuthenticatedCoursesCourseIdStreamRouteImport.update({
    id: '/stream',
    path: '/stream',
    getParentRoute: () => AuthenticatedCoursesCourseIdRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdPeopleRoute =
  AuthenticatedCoursesCourseIdPeopleRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => AuthenticatedCoursesCourseIdRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdClassworkRoute =
  AuthenticatedCoursesCourseIdClassworkRouteImport.update({
    id: '/classwork',
    path: '/classwork',
    getParentRoute: () => AuthenticatedCoursesCourseIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRouteRouteWithChildren
  '/admin/login': typeof authAdminLoginRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/settings/backup': typeof AuthenticatedSettingsBackupRoute
  '/settings/language': typeof AuthenticatedSettingsLanguageRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/scheduler': typeof AuthenticatedSettingsSchedulerRoute
  '/settings/setup': typeof AuthenticatedSettingsSetupRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/audit/': typeof AuthenticatedAuditIndexRoute
  '/bot/': typeof AuthenticatedBotIndexRoute
  '/courses/': typeof AuthenticatedCoursesIndexRoute
  '/search/': typeof AuthenticatedSearchIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/sync/': typeof AuthenticatedSyncIndexRoute
  '/todos/': typeof AuthenticatedTodosIndexRoute
  '/courses/$courseId/classwork': typeof AuthenticatedCoursesCourseIdClassworkRoute
  '/courses/$courseId/people': typeof AuthenticatedCoursesCourseIdPeopleRoute
  '/courses/$courseId/stream': typeof AuthenticatedCoursesCourseIdStreamRoute
  '/courses/$courseId/': typeof AuthenticatedCoursesCourseIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/admin/login': typeof authAdminLoginRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/settings/backup': typeof AuthenticatedSettingsBackupRoute
  '/settings/language': typeof AuthenticatedSettingsLanguageRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/scheduler': typeof AuthenticatedSettingsSchedulerRoute
  '/settings/setup': typeof AuthenticatedSettingsSetupRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/audit': typeof AuthenticatedAuditIndexRoute
  '/bot': typeof AuthenticatedBotIndexRoute
  '/courses': typeof AuthenticatedCoursesIndexRoute
  '/search': typeof AuthenticatedSearchIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/sync': typeof AuthenticatedSyncIndexRoute
  '/todos': typeof AuthenticatedTodosIndexRoute
  '/courses/$courseId/classwork': typeof AuthenticatedCoursesCourseIdClassworkRoute
  '/courses/$courseId/people': typeof AuthenticatedCoursesCourseIdPeopleRoute
  '/courses/$courseId/stream': typeof AuthenticatedCoursesCourseIdStreamRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/courses/$courseId': typeof AuthenticatedCoursesCourseIdRouteRouteWithChildren
  '/(auth)/admin/login': typeof authAdminLoginRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/_authenticated/settings/backup': typeof AuthenticatedSettingsBackupRoute
  '/_authenticated/settings/language': typeof AuthenticatedSettingsLanguageRoute
  '/_authenticated/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/_authenticated/settings/scheduler': typeof AuthenticatedSettingsSchedulerRoute
  '/_authenticated/settings/setup': typeof AuthenticatedSettingsSetupRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/audit/': typeof AuthenticatedAuditIndexRoute
  '/_authenticated/bot/': typeof AuthenticatedBotIndexRoute
  '/_authenticated/courses/': typeof AuthenticatedCoursesIndexRoute
  '/_authenticated/search/': typeof AuthenticatedSearchIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/sync/': typeof AuthenticatedSyncIndexRoute
  '/_authenticated/todos/': typeof AuthenticatedTodosIndexRoute
  '/_authenticated/courses/$courseId/classwork': typeof AuthenticatedCoursesCourseIdClassworkRoute
  '/_authenticated/courses/$courseId/people': typeof AuthenticatedCoursesCourseIdPeopleRoute
  '/_authenticated/courses/$courseId/stream': typeof AuthenticatedCoursesCourseIdStreamRoute
  '/_authenticated/courses/$courseId/': typeof AuthenticatedCoursesCourseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/login'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/courses/$courseId'
    | '/admin/login'
    | '/errors/$error'
    | '/settings/audit'
    | '/settings/backup'
    | '/settings/language'
    | '/settings/roles'
    | '/settings/scheduler'
    | '/settings/setup'
    | '/settings/users'
    | '/audit/'
    | '/bot/'
    | '/courses/'
    | '/search/'
    | '/settings/'
    | '/sync/'
    | '/todos/'
    | '/courses/$courseId/classwork'
    | '/courses/$courseId/people'
    | '/courses/$courseId/stream'
    | '/courses/$courseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/admin/login'
    | '/errors/$error'
    | '/settings/audit'
    | '/settings/backup'
    | '/settings/language'
    | '/settings/roles'
    | '/settings/scheduler'
    | '/settings/setup'
    | '/settings/users'
    | '/audit'
    | '/bot'
    | '/courses'
    | '/search'
    | '/settings'
    | '/sync'
    | '/todos'
    | '/courses/$courseId/classwork'
    | '/courses/$courseId/people'
    | '/courses/$courseId/stream'
    | '/courses/$courseId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/login'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/courses/$courseId'
    | '/(auth)/admin/login'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/audit'
    | '/_authenticated/settings/backup'
    | '/_authenticated/settings/language'
    | '/_authenticated/settings/roles'
    | '/_authenticated/settings/scheduler'
    | '/_authenticated/settings/setup'
    | '/_authenticated/settings/users'
    | '/_authenticated/audit/'
    | '/_authenticated/bot/'
    | '/_authenticated/courses/'
    | '/_authenticated/search/'
    | '/_authenticated/settings/'
    | '/_authenticated/sync/'
    | '/_authenticated/todos/'
    | '/_authenticated/courses/$courseId/classwork'
    | '/_authenticated/courses/$courseId/people'
    | '/_authenticated/courses/$courseId/stream'
    | '/_authenticated/courses/$courseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  authAdminLoginRoute: typeof authAdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/todos/': {
      id: '/_authenticated/todos/'
      path: '/todos'
      fullPath: '/todos/'
      preLoaderRoute: typeof AuthenticatedTodosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sync/': {
      id: '/_authenticated/sync/'
      path: '/sync'
      fullPath: '/sync/'
      preLoaderRoute: typeof AuthenticatedSyncIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/search/': {
      id: '/_authenticated/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof AuthenticatedSearchIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/': {
      id: '/_authenticated/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AuthenticatedCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bot/': {
      id: '/_authenticated/bot/'
      path: '/bot'
      fullPath: '/bot/'
      preLoaderRoute: typeof AuthenticatedBotIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit/': {
      id: '/_authenticated/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuthenticatedAuditIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/setup': {
      id: '/_authenticated/settings/setup'
      path: '/setup'
      fullPath: '/settings/setup'
      preLoaderRoute: typeof AuthenticatedSettingsSetupRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/scheduler': {
      id: '/_authenticated/settings/scheduler'
      path: '/scheduler'
      fullPath: '/settings/scheduler'
      preLoaderRoute: typeof AuthenticatedSettingsSchedulerRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/roles': {
      id: '/_authenticated/settings/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AuthenticatedSettingsRolesRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/language': {
      id: '/_authenticated/settings/language'
      path: '/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof AuthenticatedSettingsLanguageRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/backup': {
      id: '/_authenticated/settings/backup'
      path: '/backup'
      fullPath: '/settings/backup'
      preLoaderRoute: typeof AuthenticatedSettingsBackupRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/audit': {
      id: '/_authenticated/settings/audit'
      path: '/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AuthenticatedSettingsAuditRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/admin/login': {
      id: '/(auth)/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof authAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/courses/$courseId': {
      id: '/_authenticated/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$courseId/': {
      id: '/_authenticated/courses/$courseId/'
      path: '/'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdIndexRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRouteRoute
    }
    '/_authenticated/courses/$courseId/stream': {
      id: '/_authenticated/courses/$courseId/stream'
      path: '/stream'
      fullPath: '/courses/$courseId/stream'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdStreamRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRouteRoute
    }
    '/_authenticated/courses/$courseId/people': {
      id: '/_authenticated/courses/$courseId/people'
      path: '/people'
      fullPath: '/courses/$courseId/people'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdPeopleRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRouteRoute
    }
    '/_authenticated/courses/$courseId/classwork': {
      id: '/_authenticated/courses/$courseId/classwork'
      path: '/classwork'
      fullPath: '/courses/$courseId/classwork'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdClassworkRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAuditRoute: typeof AuthenticatedSettingsAuditRoute
  AuthenticatedSettingsBackupRoute: typeof AuthenticatedSettingsBackupRoute
  AuthenticatedSettingsLanguageRoute: typeof AuthenticatedSettingsLanguageRoute
  AuthenticatedSettingsRolesRoute: typeof AuthenticatedSettingsRolesRoute
  AuthenticatedSettingsSchedulerRoute: typeof AuthenticatedSettingsSchedulerRoute
  AuthenticatedSettingsSetupRoute: typeof AuthenticatedSettingsSetupRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAuditRoute: AuthenticatedSettingsAuditRoute,
    AuthenticatedSettingsBackupRoute: AuthenticatedSettingsBackupRoute,
    AuthenticatedSettingsLanguageRoute: AuthenticatedSettingsLanguageRoute,
    AuthenticatedSettingsRolesRoute: AuthenticatedSettingsRolesRoute,
    AuthenticatedSettingsSchedulerRoute: AuthenticatedSettingsSchedulerRoute,
    AuthenticatedSettingsSetupRoute: AuthenticatedSettingsSetupRoute,
    AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedCoursesCourseIdRouteRouteChildren {
  AuthenticatedCoursesCourseIdClassworkRoute: typeof AuthenticatedCoursesCourseIdClassworkRoute
  AuthenticatedCoursesCourseIdPeopleRoute: typeof AuthenticatedCoursesCourseIdPeopleRoute
  AuthenticatedCoursesCourseIdStreamRoute: typeof AuthenticatedCoursesCourseIdStreamRoute
  AuthenticatedCoursesCourseIdIndexRoute: typeof AuthenticatedCoursesCourseIdIndexRoute
}

const AuthenticatedCoursesCourseIdRouteRouteChildren: AuthenticatedCoursesCourseIdRouteRouteChildren =
  {
    AuthenticatedCoursesCourseIdClassworkRoute:
      AuthenticatedCoursesCourseIdClassworkRoute,
    AuthenticatedCoursesCourseIdPeopleRoute:
      AuthenticatedCoursesCourseIdPeopleRoute,
    AuthenticatedCoursesCourseIdStreamRoute:
      AuthenticatedCoursesCourseIdStreamRoute,
    AuthenticatedCoursesCourseIdIndexRoute:
      AuthenticatedCoursesCourseIdIndexRoute,
  }

const AuthenticatedCoursesCourseIdRouteRouteWithChildren =
  AuthenticatedCoursesCourseIdRouteRoute._addFileChildren(
    AuthenticatedCoursesCourseIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCoursesCourseIdRouteRoute: typeof AuthenticatedCoursesCourseIdRouteRouteWithChildren
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAuditIndexRoute: typeof AuthenticatedAuditIndexRoute
  AuthenticatedBotIndexRoute: typeof AuthenticatedBotIndexRoute
  AuthenticatedCoursesIndexRoute: typeof AuthenticatedCoursesIndexRoute
  AuthenticatedSearchIndexRoute: typeof AuthenticatedSearchIndexRoute
  AuthenticatedSyncIndexRoute: typeof AuthenticatedSyncIndexRoute
  AuthenticatedTodosIndexRoute: typeof AuthenticatedTodosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCoursesCourseIdRouteRoute:
    AuthenticatedCoursesCourseIdRouteRouteWithChildren,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAuditIndexRoute: AuthenticatedAuditIndexRoute,
  AuthenticatedBotIndexRoute: AuthenticatedBotIndexRoute,
  AuthenticatedCoursesIndexRoute: AuthenticatedCoursesIndexRoute,
  AuthenticatedSearchIndexRoute: AuthenticatedSearchIndexRoute,
  AuthenticatedSyncIndexRoute: AuthenticatedSyncIndexRoute,
  AuthenticatedTodosIndexRoute: AuthenticatedTodosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  authAdminLoginRoute: authAdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
